---
version: "2"
##checks:
##  argument-count:
##    config:
##      threshold: 5
exclude_patterns:
  - "build/"
  - "docs/"
  - "bin/"
  - "vendor/"
  - "**/Tests/"
  - "**/Behat/"
  - "**/Resources/"
  - "**/vendor/"
  - "packages/ldaplib/src/Korowai/Lib/Ldap/Adapter/ExtLdap/LdapLink.php"
  - "packages/compatlib/src/Korowai/Lib/Compat/functions/preg.php"
plugins:
  phpcodesniffer:
    enabled: true
