---
version: "2"
##checks:
##  argument-count:
##    config:
##      threshold: 5
exclude_patterns:
  - "build/"
  - "docs/"
  - "bin/"
  - "vendor/"
  - "src/Korowai/*/*/Tests/"
  - "src/Korowai/*/*/Behat/"
  - "src/Korowai/*/*/Resources/"
  - "src/Korowai/*/*/vendor/"
##plugins:
##  pep8:
##    enabled: true
##  markdownlint:
##    enabled: true
##    checks:
##      MD002:
##        enabled: false
