language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
env:
  - COVERALLS_PARALLEL=true
install:
  - travis_retry composer install --no-interaction
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml.dist
after_success:
  - travis_retry php vendor/bin/php-coveralls -v
notifications:
  webhooks: https://coveralls.io/webhook
