language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
install:
  - travis_retry composer install --no-interaction
    #  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml.dist
after_success:
  - travis_retry php vendor/bin/php-coveralls -v
