language: php
php:
  - '7.4'
  - 'nightly'
env:
  - KOROWAI_NOCOV=false
  - KOROWAI_NOCOV=true
jobs:
  allow_failures:
    - php: 'nightly'
install:
  - php -i
  - travis_retry composer install --no-interaction
script:
  - mkdir -p build/logs
  - if $KOROWAI_NOCOV; then
      php vendor/bin/phpunit -c phpunit-nocov.xml.dist;
    else
      php vendor/bin/phpunit -c phpunit.xml.dist;
    fi
after_success:
  - if ! $KOROWAI_NOCOV; then curl -s https://codecov.io/bash | bash; fi
