version: '3.7'
services:
  php-cli:
    image: "korowai/php:${COMPOSE_CLI_TAG:-cli}"
    depends_on:
      - ldap-service
    volumes:
      - .:/home/php/project
    user: "${COMPOSE_USER:?you must set the COMPOSE_USER environment variable}"
    entrypoint: [ "dockerize", "-wait", "tcp://ldap-service:389", "-timeout", "10s" ]

  http-service:
    image: "korowai/php:${COMPOSE_APACHE_TAG:-apache}"
    volumes:
      - .:/korowai
    working_dir: /korowai

  ldap-service:
    command: [ --copy-service, --loglevel, debug]
    image: "korowai/openldap:${COMPOSE_OPENLDAP_TAG:-latest}"
    volumes:
      - ./src/Korowai/Component/Ldap/Resources/ldif/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
