version: 2.1
jobs:
  build_api_docs:
    docker:
      - image: korowai/sami:latest
    steps:
      - checkout
      - run: build

workflows:
  version: 2.1
  build_docs:
    jobs:
      - build_api_docs
