version: 2.1
jobs:
  build_api_docs:
    docker:
      - image: circleci/php:7.3.5-cli
    steps:
      - checkout
      - run:
          - php bootstrap-dev
          - php composer install

workflows:
  version: 2.1
  build_docs:
    jobs:
      - build_api_docs
