version: 2.1

sf_deploy_env: &sf_deploy_env
  SF_DEPL_HOST: web.sourceforge.net
  SF_DOCS_DIR: /home/project-web/korowai-framework/htdocs/docs

sf_deploy_command: &sf_deploy_command
  command: |
    sudo apt-get -y update && sudo apt-get -y install rsync &&
    ssh-keyscan "${SF_DEPL_HOST}" >> ~/.ssh/known_hosts &&
    ( cd "${DOCS_DIR}" && rsync -aivz --delete ./ "${SF_DEPL_USER}@${SF_DEPL_HOST}:${SF_DOCS_DIR}/${CIRCLE_BRANCH}/" );


ssh_keys: &ssh_keys
  fingerprints:
    - "f8:01:5a:e4:53:1c:dc:9e:f8:a4:dc:b3:a0:e3:80:95"

jobs:
  build_sami_docs:
    docker:
      - image: circleci/php:7.3.5-cli

    steps:
      - checkout

      - run:
          name: Install Sami
          command: |
            curl -s -L -o sami.phar http://get.sensiolabs.org/sami.phar &&
            chmod a+x sami.phar

      - run:
          name: Build docs
          command: ./sami.phar update --force -vvv docs/sami/sami.conf.php

      - persist_to_workspace:
          root: docs/build/html
          paths:
            - api/

  build_sphinx_docs:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - add_ssh_keys:
          <<: *ssh_keys

      - run:
          name: Setup virtualenv
          command: python -m venv ~/.venv

      - run:
          name: Install sphinx
          command: |
            . ~/.venv/bin/activate &&
            python -m pip install -U --progress-bar off pip &&
            python -m pip install -U --progress-bar off -r docs/sphinx/requirements.txt

      - run:
          name: Build user docs
          command: |
            . ~/.venv/bin/activate &&
            sphinx-build docs/sphinx docs/build/html

      - persist_to_workspace:
          root: docs/build/html
          paths:
            - ./

  deploy_docs:
    docker:
      - image: circleci/python:3.7

    environment:
      DOCS_DIR: docs/build/html
      <<: *sf_deploy_env

    steps:
      - attach_workspace:
          at: docs/build/html

      - run:
          name: Deploy to Source Forge
          <<: *sf_deploy_command

workflows:
  version: 2.1
  build_docs:
    jobs:
      - build_sami_docs
      - build_sphinx_docs
      - deploy_docs:
          requires:
            - build_sami_docs
            - build_sphinx_docs
          filters:
            branches:
              only:
                - master
                - devel
