version: 2.1

jobs:
  build_api_docs:
    docker:
      - image: circleci/php:7.3.5-cli
    steps:
      - checkout

      - run:
          name: Install Sami
          command: |
            curl -s -L -o sami.phar http://get.sensiolabs.org/sami.phar &&
            chmod a+x sami.phar

      - run:
          name: Build API docs
          command: ./sami.phar update --force -vvv docs/sami/sami.conf.php

      - run:
          name: Make an API doc tarball
          command: |
            (cd docs/build/html && tar -czf "api.tar.gz" api)

      - store_artifacts:
          path: docs/build/html/api.tar.gz
          destination: "api.tar.gz"

  build_user_docs:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - run:
          name: Setup virtualenv
          command: python -m venv ~/.venv

      - run:
          name: Install sphinx
          command: |
            . ~/.venv/bin/activate &&
            python -m pip install -U --progress-bar off pip &&
            python -m pip install -U --progress-bar off -r docs/sphinx/requirements.txt

      - run:
          name: Build user docs
          command: |
            . ~/.venv/bin/activate &&
            sphinx-build docs/sphinx docs/build/html

workflows:
  version: 2.1
  build_docs:
    jobs:
      - build_api_docs
      - build_user_docs
