version: 2.1
jobs:
  build_api_docs:
    docker:
      - image: circleci/php:7.3.5-cli
    steps:
      - checkout
      - run:
          - curl -s -L -o /usr/local/bin/sami http://get.sensiolabs.org/sami.phar
          - chmod a+x /usr/local/bin/sami
          - sami update docs/sami/sami.conf.php

workflows:
  version: 2.1
  build_docs:
    jobs:
      - build_api_docs
