version: 2.1

jobs:
  build_api_docs:
    docker:
      - image: circleci/php:7.3.5-cli
    steps:
      - checkout

      - run:
          name: Install Sami
          command: |
            curl -s -L -o sami.phar http://get.sensiolabs.org/sami.phar &&
            chmod a+x sami.phar

      - run:
          name: Build API docs
          command: ./sami.phar update --force -vvv docs/sami/sami.conf.php

  build_user_docs:
    docker:
      - image: korowai/sphinx:latest
    steps:
      - checkout
      - run:
          name: Build user docs
          command: build

workflows:
  version: 2.1
  build_docs:
    jobs:
      - build_api_docs
      - build_user_docs
