version: '3'
services:
  sphinx:
    image: korowai/sphinx
    ports:
      - "8000:8000"
    volumes:
      - ../:/home/sphinx/project

  sami:
    image: korowai/sami
    ports:
      - "8001:8001"
    volumes:
      - ../:/home/sami/project
