version: '3.7'
services:
  sphinx:
    image: "korowai/sphinx:${KRW_SPHINX_TAG:-latest}"
    ports:
      - "8000:8000"
    volumes:
      - ../:/home/sphinx/project
    user: "${KRW_UID:-1000}:${KRW_GID:-1000}"

  sami:
    image: "korowai/sami:${KRW_SAMI_TAG:-latest}"
    ports:
      - "8001:8001"
    volumes:
      - ../:/home/sami/project
    user: "${KRW_UID:-1000}:${KRW_GID:-1000}"

  phpdoc:
    image: "phpdoc/phpdoc:${KRW_PHPDOC_TAG:-develop}"
    volumes:
      - ../:/data
    user: "${KRW_UID:-1000}:${KRW_GID:-1000}"
