version: '3'
services:
  sphinx:
    build:
      context: ./sphinx/
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/python/docs
      - ../src:/home/python/src:ro

  sami:
    image: korowai/sami
    ports:
      - "8001:8001"
    volumes:
      - ../:/home/sami/project
