on:
  - pull_request
  - push

name: CI

jobs:
  coding-guidelines:
    name: Coding Guidelines

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Instal PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: php-cs-fixer:2.16.3

      - name: Run friendsofphp/php-cs-fixer
        run: php-cs-fixer fix --diff-format=udiff --dry-run --show-progress=dots --using-cache=no --verbose
